name: Go Ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get -f install libpixman-1-0
    - name: Setup Go 1.24.3
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.3
    - name: Tests
      run: go test -v ./...
    - name: Vet
      run: go vet ./...
    - name: Benchmarks
      run: go test -bench=. -benchtime=5s -run=^$
    - name: Build blit
      run: go build -o blit ./cmd/blit
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: brew install pixman
    - name: Setup Go 1.24.3
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.3
    - name: Tests
      run: go test -v ./...
