name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: sudo apt-get update && sudo apt-get -f install libpixman-1-0
    - name: Setup Go 1.24.3
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.3